apiVersion: apps/v1
kind: Deployment
metadata:
  name: gl-demo
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: 206809158604.dkr.ecr.us-east-1.amazonaws.com/hello-world:latest
        ports:
        - containerPort: 80
